version: "2"

run:
  timeout: 5m
  tests: true
  go: '1.25'

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam

  settings:
    errcheck:
      check-blank: false  # Don't check blank identifier assignments
      exclude-functions:
        - (*bytes.Buffer).Write
        - (*bytes.Buffer).WriteByte
        - (*bytes.Buffer).WriteRune
        - (*bytes.Buffer).WriteString
        - io.WriteString
        - (io.ReadSeeker).Seek

    govet:
      disable:
        - shadow  # Can be overly strict

    staticcheck:
      checks: ["all"]

    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-naming
        - name: error-return
        - name: error-strings
        - name: errorf
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: empty-block
        - name: superfluous-else
        - name: unreachable-code
        - name: redefines-builtin-id
        # Disabled rules
        - name: exported
          disabled: true  # Can be noisy for public API
        - name: package-comments
          disabled: true  # Not all packages need package comments
        - name: unused-parameter
          disabled: true  # Can be noisy with interface implementations

    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
      disabled-checks:
        - whyNoLint
        - unnamedResult

  exclusions:
    rules:
      # Exclude some linters from test files
      - path: _test\.go
        linters:
          - errcheck
          - staticcheck
      # Exclude example code from some checks
      - path: example/
        linters:
          - errcheck
          - staticcheck
      # Exclude ST1003 (naming) as it would require API breaking changes
      - linters:
          - staticcheck
        text: "ST1003"
      # Exclude some comment style checks
      - linters:
          - staticcheck
        text: "ST1020|ST1021|ST1000"

formatters:
  enable:
    - goimports
  exclusions:
    # Don't reformat existing code
    paths:
      - ".*\\.go"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    text:
      path: stdout
      print-linter-name: true
  sort-order:
    - linter
    - file
